Started logging messages at Thu Apr 23 11:35:10 2020
Info:    Using UV tolerance 1e-006
Info:    Using UV tolerance 1e-006
Info:    HwNlibToTSLib options selected:
Info:        Points: Off
Info:        Curves: On
Info:        Surfaces: Off
Info:        BReps: On
Info:        Do not create IwAssembly/IwAssemblyInstance objects
Info:        Making untrimmed surfaces into BReps
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW SAT v1.2.6-maint
Info:    Reading 
Info:    Processing 
Info:    Transferring 
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 1 B-reps in file
Info:    Found 105 B-rep faces in file
Info:    
Info:    Using 3D tolerance 1e-006
Info:    Working on 0
Info:        Working on 84
Info:            Created 
Info:        Working on 85
Info:            Created 
Info:        Working on 124
Info:            Created 
Info:        Working on 179
Info:            Created 
Info:        Working on 195
Info:            Created 
Info:        Working on 134
Info:            Created 
Info:        Working on 10
Info:            Created 
Info:        Working on 113
Info:            Created 
Info:        Working on 114
Info:            Created 
Info:        Working on 165
Info:            Created 
Info:        Working on 166
Info:            Created 
Info:        Working on 14
Info:            Created 
Info:        Working on 160
Info:            Created 
Info:        Working on 224
Info:            Created 
Info:        Working on 19
Info:            Created 
Info:        Working on 223
Info:            Created 
Info:        Working on 295
Info:            Created 
Info:        Working on 296
Info:            Created 
Info:        Working on 28
Info:            Created 
Info:        Working on 227
Info:            Created 
Info:        Working on 49
Info:            Created 
Info:        Working on 89
Info:            Created 
Info:        Working on 351
Info:            Created 
Info:        Working on 147
Info:            Created 
Info:        Working on 647
Info:            Created 
Info:        Working on 338
Info:            Created 
Info:        Working on 485
Info:            Created 
Info:        Working on 214
Info:            Created 
Info:        Working on 802
Info:            Created 
Info:        Working on 811
Info:            Created 
Info:        Working on 1232
Info:            Created 
Info:        Working on 1233
Info:            Created 
Info:        Working on 290
Info:            Created 
Info:        Working on 590
Info:            Created 
Info:        Working on 1081
Info:            Created 
Info:        Working on 389
Info:            Created 
Info:        Working on 430
Info:            Created 
Info:        Working on 819
Info:            Created 
Info:        Working on 532
Info:            Created 
Info:        Working on 820
Info:            Created 
Info:        Working on 1076
Info:            Created 
Info:        Working on 1650
Info:            Created 
Info:        Working on 726
Info:            Created 
Info:        Working on 431
Info:            Created 
Info:        Working on 601
Info:            Created 
Info:        Working on 583
Info:            Created 
Info:        Working on 822
Info:            Created 
Info:        Working on 809
Info:            Created 
Info:        Working on 693
Info:            Created 
Info:        Working on 924
Info:            Created 
Info:        Working on 1045
Info:            Created 
Info:        Working on 1056
Info:            Created 
Info:        Working on 1564
Info:            Created 
Info:        Working on 1567
Info:            Created 
Info:        Working on 1186
Info:            Created 
Info:        Working on 789
Info:            Created 
Info:        Working on 1339
Info:            Created 
Info:        Working on 1336
Info:            Created 
Info:        Working on 573
Info:            Created 
Info:        Working on 1068
Info:            Created 
Info:        Working on 1064
Info:            Created 
Info:        Working on 1069
Info:            Created 
Info:        Working on 1329
Info:            Created 
Info:        Working on 1853
Info:            Created 
Info:        Working on 1341
Info:            Created 
Info:        Working on 574
Info:            Created 
Info:        Working on 800
Info:            Created 
Info:        Working on 780
Info:            Created 
Info:        Working on 1071
Info:            Created 
Info:        Working on 1052
Info:            Created 
Info:        Working on 920
Info:            Created 
Info:        Working on 1182
Info:            Created 
Info:        Working on 1294
Info:            Created 
Info:        Working on 1305
Info:            Created 
Info:        Working on 1753
Info:            Created 
Info:        Working on 1756
Info:            Created 
Info:        Working on 1430
Info:            Created 
Info:        Working on 1027
Info:            Created 
Info:        Working on 1556
Info:            Created 
Info:        Working on 1553
Info:            Created 
Info:        Working on 768
Info:            Created 
Info:        Working on 1317
Info:            Created 
Info:        Working on 1313
Info:            Created 
Info:        Working on 1318
Info:            Created 
Info:        Working on 1546
Info:            Created 
Info:        Working on 2008
Info:            Created 
Info:        Working on 1558
Info:            Created 
Info:        Working on 769
Info:            Created 
Info:        Working on 1038
Info:            Created 
Info:        Working on 1018
Info:            Created 
Info:        Working on 1320
Info:            Created 
Info:        Working on 1301
Info:            Created 
Info:        Working on 1178
Info:            Created 
Info:        Working on 1426
Info:            Created 
Info:        Working on 209
Info:            Created 
Info:        Working on 210
Info:            Created 
Info:        Working on 143
Info:            Created 
Info:        Working on 280
Info:            Created 
Info:        Working on 376
Info:            Created 
Info:        Working on 516
Info:            Created 
Info:        Working on 700
Info:            Created 
Info:        Working on 525
Info:            Created 
Info:        Working on 382
Info:            Created 
Info:        Working on 206
Info:            Created 
Info:        Working on 677
Info:            Created 
Info:        Working on 906
Info:            Created 
Info:        Working on 683
Info:            Created 
Info:        Working on 494
Info:            Created 
Info:        Working on 271
Info:            Created 
Info:        Working on 713
Info:            Created 
Info:        Working on 366
Info:            Created 
Info:        Working on 503
Info:            Created 
Info:        Working on 1204
Info:            Created 
Info:        Working on 1175
Info:            Created 
Info:        Working on 696
Info:            Created 
Info:        Working on 366
Info:            Created 
Info:        Working on 461
Info:            Created 
Info:        Working on 876
Info:            Created 
Info:        Working on 143
Info:            Created 
Info:        Working on 1423
Info:            Created 
Info:        Working on 1440
Info:            Created 
Info:        Working on 1200
Info:            Created 
Info:        Working on 941
Info:            Created 
Info:        Working on 1442
Info:            Created 
Info:        Working on 712
Info:            Created 
Info:        Working on 1140
Info:            Created 
Info:        Working on 1633
Info:            Created 
Info:        Working on 1645
Info:            Created 
Info:        Working on 206
Info:            Created 
Info:        Working on 640
Info:            Created 
Info:        Working on 385
Info:            Created 
Info:        Working on 329
Info:            Created 
Info:        Working on 385
Info:            Created 
Info:        Working on 1463
Info:            Created 
Info:        Working on 1464
Info:            Created 
Info:        Working on 1670
Info:            Created 
Info:        Working on 1671
Info:            Created 
Info:        Working on 529
Info:            Created 
Info:        Working on 1279
Info:            Created 
Info:        Working on 1748
Info:            Created 
Info:        Working on 722
Info:            Created 
Info:        Working on 1006
Info:            Created 
Info:        Working on 1536
Info:            Created 
Info:        Working on 958
Info:            Created 
Info:        Working on 1007
Info:            Created 
Info:        Working on 1537
Info:            Created 
Info:        Working on 1220
Info:            Created 
Info:        Working on 1275
Info:            Created 
Info:        Working on 1741
Info:            Created 
Info:        Working on 1452
Info:            Created 
Info:        Working on 1527
Info:            Created 
Info:        Working on 2101
Info:            Created 
Info:        Working on 1745
Info:            Created 
Info:        Working on 1712
Info:            Created 
Info:        Working on 1724
Info:            Created 
Info:        Working on 2038
Info:            Created 
Info:        Working on 2043
Info:            Created 
Info:        Working on 1920
Info:            Created 
Info:        Working on 1508
Info:            Created 
Info:        Working on 1918
Info:            Created 
Info:        Working on 1915
Info:            Created 
Info:        Working on 1267
Info:            Created 
Info:        Working on 1735
Info:            Created 
Info:        Working on 1731
Info:            Created 
Info:        Working on 1268
Info:            Created 
Info:        Working on 1736
Info:            Created 
Info:        Working on 1519
Info:            Created 
Info:        Working on 1499
Info:            Created 
Info:        Working on 1905
Info:            Created 
Info:        Working on 1738
Info:            Created 
Info:        Working on 1720
Info:            Created 
Info:        Working on 2005
Info:            Created 
Info:        Working on 1908
Info:            Created 
Info:        Working on 1872
Info:            Created 
Info:        Working on 1883
Info:            Created 
Info:        Working on 2109
Info:            Created 
Info:        Working on 2112
Info:            Created 
Info:        Working on 2040
Info:            Created 
Info:        Working on 1694
Info:            Created 
Info:        Working on 2033
Info:            Created 
Info:        Working on 2030
Info:            Created 
Info:        Working on 1487
Info:            Created 
Info:        Working on 1893
Info:            Created 
Info:        Working on 1890
Info:            Created 
Info:        Working on 1488
Info:            Created 
Info:        Working on 1894
Info:            Created 
Info:        Working on 1705
Info:            Created 
Info:        Working on 1685
Info:            Created 
Info:        Working on 2023
Info:            Created 
Info:        Working on 1896
Info:            Created 
Info:        Working on 1879
Info:            Created 
Info:        Working on 1850
Info:            Created 
Info:        Working on 2007
Info:            Created 
Info:        Working on 629
Info:            Created 
Info:        Working on 1136
Info:            Created 
Info:        Working on 1447
Info:            Created 
Info:        Working on 1133
Info:            Created 
Info:        Working on 667
Info:            Created 
Info:        Working on 451
Info:            Created 
Info:        Working on 189
Info:            Created 
Info:        Working on 899
Info:            Created 
Info:        Working on 900
Info:            Created 
Info:        Working on 1161
Info:            Created 
Info:        Working on 1162
Info:            Created 
Info:        Working on 257
Info:            Created 
Info:        Working on 1157
Info:            Created 
Info:        Working on 1414
Info:            Created 
Info:        Working on 342
Info:            Created 
Info:        Working on 1412
Info:            Created 
Info:        Working on 1642
Info:            Created 
Info:        Working on 469
Info:            Created 
Info:        Working on 651
Info:            Created 
Info:        Working on 1860
Info:            Created 
Info:        Working on 880
Info:            Created 
Info:        Working on 2014
Info:            Created 
Info:        Working on 1144
Info:            Created 
Info:        Working on 2104
Info:            Created 
Info:        Working on 1403
Info:            Created 
Info:        Working on 1643
Info:            Created 
Info:        Working on 904
Info:            Created 
Info:        Working on 954
Info:            Created 
Info:        Working on 869
Info:            Created 
Info:        Working on 1167
Info:            Created 
Info:        Working on 636
Info:            Created 
Info:        Working on 864
Info:            Created 
Info:        Working on 1865
Info:            Created 
Info:        Working on 206
Info:            Created 
Info:        Working on 1659
Info:            Created 
Info:        Working on 1399
Info:            Created 
Info:        Working on 1189
Info:            Created 
Info:        Working on 1399
Info:            Created 
Info:        Working on 953
Info:            Created 
Info:        Working on 1215
Info:            Created 
Info:        Working on 933
Info:            Created 
Info:        Working on 1117
Info:            Created 
Info:        Working on 1614
Info:            Created 
Info:        Working on 1964
Info:            Created 
Info:        Working on 2082
Info:            Created 
Info:        Working on 2085
Info:            Created 
Info:        Working on 2137
Info:            Created 
Info:        Working on 2124
Info:            Created 
Info:        Working on 2065
Info:            Created 
Info:        Working on 2064
Info:            Created 
Info:        Working on 2153
Info:            Created 
Info:        Working on 2157
Info:            Created 
Info:        Working on 2156
Info:            Created 
Info:        Working on 2073
Info:            Created 
Info:        Working on 1786
Info:            Created 
Info:        Working on 1595
Info:            Created 
Info:        Working on 1594
Info:            Created 
Info:        Working on 1948
Info:            Created 
Info:        Working on 2128
Info:            Created 
Info:        Working on 2138
Info:            Created 
Info:        Working on 2090
Info:            Created 
Info:        Working on 1966
Info:            Created 
Info:        Working on 1793
Info:            Created 
Info:        Working on 1376
Info:            Created 
Info:        Working on 1118
Info:            Created 
Info:        Working on 1192
Info:            Created 
Info:        Working on 1810
Info:            Created 
Info:        Working on 1978
Info:            Created 
Info:        Working on 1436
Info:            Created 
Info:        Working on 1979
Info:            Created 
Info:        Working on 1971
Info:            Created 
Info:        Working on 1654
Info:            Created 
Info:        Working on 1856
Info:            Created 
Info:        Working on 1987
Info:            Created 
Info:        Working on 1835
Info:            Created 
Info:        Working on 2011
Info:            Created 
Info:        Working on 1989
Info:            Created 
Info:        Working on 2103
Info:            Created 
Info:        Working on 1836
Info:            Created 
Info:        Working on 1993
Info:            Created 
Info:        Working on 1387
Info:            Created 
Info:        Working on 1109
Info:            Created 
Info:        Working on 1601
Info:            Created 
Info:        Working on 852
Info:            Created 
Info:        Working on 1780
Info:            Created 
Info:        Working on 1589
Info:            Created 
Info:        Working on 2100
Info:            Created 
Info:        Working on 2142
Info:            Created 
Info:        Working on 1946
Info:            Created 
Info:        Working on 2121
Info:            Created 
Info:        Working on 173
Info:            Created 
Info:        Working on 851
Info:            Created 
Info:        Working on 237
Info:            Created 
Info:        Working on 318
Info:            Created 
Info:        Working on 1368
Info:            Created 
Info:        Working on 1369
Info:            Created 
Info:        Working on 435
Info:            Created 
Info:        Working on 605
Info:            Created 
Info:        Working on 826
Info:            Created 
Info:        Working on 1945
Info:            Created 
Info:        Working on 1085
Info:            Created 
Info:        Working on 2058
Info:            Created 
Info:        Working on 1350
Info:            Created 
Info:        Working on 1571
Info:            Created 
Info:        Working on 2141
Info:            Created 
Info:        Working on 2099
Info:            Created 
Info:        Working on 1762
Info:            Created 
Info:        Working on 1926
Info:            Created 
Info:        Working on 2045
Info:            Created 
Info:        Working on 1126
Info:            Created 
Info:        Created 
Info:    Working on BRep 0
Info:        Using 3D tolerance 0.000202086
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Finished with 
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                 0 found       0 created       0 failed
Info:    Surfaces:               0 found       0 created       0 failed
Info:    Trimmed Surfaces:       0 found       0 created       0 failed
Info:    Breps:                  1 found       1 created       0 failed
Finished logging messages at Thu Apr 23 11:35:10 2020
